#!/usr/bin/env bash
# Script that configures Nginx server with a custom header

apt-get update
apt-get -y install nginx
sed -i "/server_name _;/a add_header X-Served-By '$HOSTNAME';" /etc/nginx/sites-available/default
service nginx restart
