#!/bin/env bash

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display "To infinity and beyond" indefinitely
while :
do
    echo "To infinity and beyond"
done

# Handle the SIGTERM signal
trap 'echo "I hate the kill command"; exit' SIGTERM

# Handle the SIGINT signal
trap 'echo "Y U no love me?!"' SIGINT

# Handle the SIGQUIT and SIGTERM signals
trap 'rm /var/run/myscript.pid; exit' SIGQUIT SIGTERM
